language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

services:
  - postgresql

before_script:
  - cargo install diesel_cli
  - cd tests && DATABASE_URL=postgresql://postgres@localhost:5432/isolang diesel database reset

script:
  - cargo build --verbose --all
  - cargo build --verbose --all --features serde_serialize
  - cargo build --verbose --all --features diesel_sql
  - cargo build --verbose --all --features "serde_serialize diesel_sql"
  - DATABASE_URL=postgresql://postgres@localhost:5432/isolang cargo test --verbose --all --all-features