language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose --all
  - cargo build --verbose --all --features serde_serialize
  - cargo test --verbose --all --features serde_serialize