[package]
authors = ["Sebastian Humenda <shumenda@gmx.de>"]
build = "build.rs"
description = "Efficient, static lookup table for ISO 639 language codes"
documentation = "https://docs.rs/isolang"
keywords = [
    "iso",
    "language",
]
license = "Apache-1.0"
name = "isolang"
readme = "README.md"
repository = "https://github.com/humenda/isolang-rs"
version = "0.2.0"

[build-dependencies]
phf_codegen = "0.7.21"

[dependencies]
phf = "0.7.21"

[dependencies.serde]
optional = true
version = "1.0.21"

[dependencies.serde_derive]
optional = true
version = "1.0.21"

[features]
default = []
serde_serialize = [
    "serde",
    "serde_derive",
]
