[package]
name = "isolang"
version = "0.1.0"
description = "Static lookup table for ISO-639 1 and 3 letter language codes"
authors = ["Sebastian Humenda <shumenda@gmx.de>"]
repository = "https://github.com/humenda/isolang-rust"
build = "build.rs"

[dependencies]
phf = "*"

[build-dependencies]
phf_codegen = "*"
