[package]
name = "isolang"
version = "0.1.1"
description = "Efficient, static lookup table for ISO 639 language codes"
documentation = "https://docs.rs/isolang"
authors = ["Sebastian Humenda <shumenda@gmx.de>"]
repository = "https://github.com/humenda/isolang-rs"
build = "build.rs"
readme = "README.md"
keywords = ["iso", "language"]
license = "Apache-1.0"

[dependencies]
phf = "0.7.21"

[build-dependencies]
phf_codegen = "0.7.21"
